work_dir: ./work_dir/nmfs/normal_joint_hand
seed: 15
# feeder
feeder: feeders.feeder_nmfs_csl.Feeder_normal
train_feeder_args:
  data_path: data/NMFs-CSL/nmf_train.npz
  debug: False
  random_choose: True
  random_shift: True
  random_move: True
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/NMFs-CSL/nmf_test.npz     #valid和test相同
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 457
  num_point: 66
  num_person: 1
  in_channels: 3
  graph: graph.nmfs_graph.Graph
  # head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'hand'

#optim
weight_decay: 0.0004
base_lr: 0.1      #fintune
lr_decay_rate: 0.1
step: [35,55]
warm_up_epoch: 20
lr_ratio: 0.001

# training
device: [0]
batch_size: 16
test_batch_size: 16
num_epoch: 150
nesterov: True
save_epoch: 10
save_interval: 2