work_dir: ./work_dir/nmfs/confusing_joint_gcn_hand
phase: train
seed: 17

# feeder
feeder: feeders.feeder_nmfs_csl.Feeder_confusing
train_feeder_args:
  data_path: data/NMFs-CSL/nmf_train.npz
  debug: False
  random_choose: True
  random_shift: True
  random_move: True
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/NMFs-CSL/nmf_test.npz     #valid和test相同
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 610
  num_point: 66
  num_person: 1
  in_channels: 3
  graph: graph.nmfs_graph.Graph
  # head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'hand'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: 0
batch_size: 32
test_batch_size: 32
num_epoch: 150
nesterov: True
save_epoch: 10
save_interval: 2